language: R
sudo: false
cache: packages
r_packages:
- covr
before_install:
# geo packages for sf
- sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
- sudo apt-get --yes --force-yes update -qq
- sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
# voro++ installation
- wget http://math.lbl.gov/voro++/download/dir/voro++-0.4.6.tar.gz
- tar xzf voro++-0.4.6.tar.gz
- cd voro++-0.4.6
- make 
- sudo make install 
- cd .. 
- rm -r voro++-0.4.6 
- rm voro++-0.4.6.tar.gz
after_success:
- Rscript -e 'library(covr); codecov()'
