language: R
sudo: false
cache: packages
r_packages:
- covr
before_install:
- sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
- sudo apt-get --yes --force-yes update -qq
- sudo apt-get install --yes libudunits2-dev
- sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev
after_success:
- Rscript -e 'library(covr); codecov()'
