language: R
dist: bionic
addons:
  apt:
    sources:
    - ppa:ubuntugis/ubuntugis-unstable
    packages:
    - voro++ 
    - libudunits2-dev 
    - libproj-dev 
    - libgeos-dev 
    - libgdal-dev
sudo: false
cache: packages
r_packages:
- covr
after_success:
- Rscript -e 'library(covr); codecov()'
